name: Latest
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Build:
    name: "Build"
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        shell: pwsh
        run: |
          ./Build.ps1 -Stages Build,Test,Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_REGISTRY: "docker.io"
          DOCKER_TAGS: "rolling"

  Linting:
    name: "Linting"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: false

      - name: "Script Analyser"
        shell: pwsh
        run: |
          $InformationPreference = "Continue"
          $ErrorActionPreference = "Stop"

          Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser
          Import-Module PSScriptAnalyzer
          Invoke-ScriptAnalyzer -IncludeDefaultRules -Recurse -EnableExit .
