name: Versioned
on:
  push:
    tags:
      - "v*"

jobs:
  Release:
    name: "Release"
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Release
        shell: pwsh
        run: |
          ./Build.ps1 -Stages Build,Test,Release,Push,Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_REGISTRY: "docker.io"
          DOCKER_TAGS: "latest"
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
